### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by marciozomb13**

### CODE REVIEW

**Review by Krishna-G-OP — COMMENTED** [review]
Thanx for your contribution
It is being reviewed. 
🙂🙂

**Comment by DP-Hridayan** [comment]
This is the strings file in values, not the Portuguese one !

**Comment by marciozomb13** [comment]
> This is the strings file in values, not the Portuguese one !

Jesus, my bad. I'll pr the right one later. My apologies.

**Comment by DP-Hridayan** [comment]
No problem , its not urgent at all !

**Pull request closed without merging**
